---
engines:
  eslint:
    enabled: true
    channel: eslint-2
    exclude_fingerprints:
    - 31f7086219bda8adf6926f08dafb533e
  fixme:
    enabled: true
ratings:
  paths:
  - source/**
exclude_paths:
- coverage/**/*
- node_modules/**/*
