dist: trusty
sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '7'
  - '6'
  - '5'
before_script:
  - npm prune
  - npm run scripts && npm run styles
after_success:
  - npm run semantic-release
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
branches:
  only:
    - master
addons:
  code_climate:
    repo_token: 1d359c8ec322c5371b0e4785740b1bbf21e5b7d61e836078077c87cd730ec017
